name: Create_poll

on:
  workflow_dispatch:

jobs:
  send-message:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Send Telegram message
      env:
        Bot_Token: ${{ secrets.Bot_Token }}
        Chat_Id: ${{ secrets.Chat_Id }}
      run: node luzhniki-football-bot.js
