name: Create poll
on:
  schedule:
    - cron: "*/5 * * * *" # Запуск каждые 5 минут
  workflow_dispatch: # Опционально: позволяет запускать задачу вручную из интерфейса GitHub

jobs:
  poll:
    runs-on: ubuntu-latest
    steps:
      - run: echo "DATE=$(TZ='Europe/Moscow' date +'%d.%m')" >> $GITHUB_ENV
      - name: Create poll
        run: |
          curl -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendPoll" \
            -H "Content-Type: application/json" \
            -d '{
              "chat_id": "'"$CHAT_ID"'",
              "question": "Сбор на '"$DATE"'",
              "options": [
          "Запасной пропускаю ❌",
          "Играю 🟢",
          "Играю 🟠",
          "Приглашенная звезда ⭐",
          "Основной пропускаю ❌",
          "Запасной играю"],
              "is_anonymous": false
            }'
        env:
          BOT_TOKEN: ${{ secrets.Bot_Token }}
          CHAT_ID: ${{ secrets.Chat_Id }}
