name: Create poll
on: workflow_dispatch

jobs:
  poll:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendPoll" \
            -d "chat_id=$CHAT_ID" \
            -d "question=Кто идет в Лужники в субботу?" \
            -d "options=['✅ Пойду','❌ Не смогу','🤔 Еще думаю']" \
            -d "is_anonymous=false"
        env:
          BOT_TOKEN: ${{ secrets.Bot_Token }}
          CHAT_ID: ${{ secrets.Chat_Id }}
